export enum Input {
  Email = 'email',
  Password = 'password',
  NewPassword = 'newPassword',
  FirstName = 'firstName',
  LastName = 'lastName',
  Street = 'streetName',
  Country = 'country',
  City = 'city',
  PostalCode = 'postalCode',
  Date = 'date',
  Month = 'month',
  Year = 'year',
  IsDefault = 'isDefault',
}
