name: Tests

on:
  pull_request:
    branches: [ 'sprint_2/login-registration-main', 'sprint_3/catalog-product-profile' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Tests
        run: |
          npm i
          npm run test
